name: whatsapp_messenger
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # Dependencies - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  flutter_native_splash: ^2.4.1
  country_picker: ^2.0.26
  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.4
  flutter_riverpod: ^2.6.1
  image_picker: ^1.0.8
  photo_manager: ^3.6.1
  flutter_contacts: ^1.1.9
  url_launcher: ^6.3.0
  firebase_database: ^11.1.4
  page_transition: ^2.1.0
  cached_network_image: ^3.4.1
  intl: ^0.19.0
  uuid: ^4.5.1
  custom_clippers: ^2.0.0
  shimmer: ^3.0.0
  fluttertoast: ^8.2.8
  giphy_picker: ^3.0.2
  get_it: ^8.0.2
  agora_uikit: ^1.3.10
  file_picker: ^8.0.7
  get_time_ago: ^2.0.0

# Splash - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
flutter_native_splash:
  color: "#FFFFFF"
  color_dark: "#111B21"
  image: assets/images/splash_light.png
  image_dark: assets/images/splash_dark.png
  android_12:
    color: "#FFFFFF"
    color_dark: "#111B21"
    image: assets/images/splash_light.png
    image_dark: assets/images/splash_dark.png
    icon_background_color: "#FFFFFF"
    icon_background_color_dark: "#111B21"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true

  # Assets - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  assets:
    - assets/images/

  # Fonts - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - - -
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Light.ttf
          weight: 300
        - asset: assets/fonts/Roboto-Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto-Medium.ttf
          weight: 500
        - asset: assets/fonts/Roboto-Bold.ttf
          weight: 700
        - asset: assets/fonts/Roboto-Black.ttf
          weight: 900